--------------------------------------------------------
--  Fichier créé - mercredi-mai-11-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROFIL" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"DATEN" DATE, 
	"PHONE" NUMBER, 
	"MAILUP10" VARCHAR2(50 BYTE), 
	"MAILPERSO" VARCHAR2(50 BYTE), 
	"NATION" VARCHAR2(50 BYTE), 
	"UNIV" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(50 BYTE), 
	"AVATAR" BFILE, 
	"DROIT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PROFIL
SET DEFINE OFF;
Insert into SYSTEM.PROFIL (ID,NOM,PRENOM,DATEN,PHONE,MAILUP10,MAILPERSO,NATION,UNIV,PASS,AVATAR,DROIT) values ('yolo','caron','kevin',to_date('12/05/16','DD/MM/RR'),'1234567890',null,'edt','fr','not','abc',null,'v');
Insert into SYSTEM.PROFIL (ID,NOM,PRENOM,DATEN,PHONE,MAILUP10,MAILPERSO,NATION,UNIV,PASS,AVATAR,DROIT) values ('pigeon','t','t',to_date('09/05/16','DD/MM/RR'),'1111111111',null,'abc@abc.fr','fr','not','reddit',null,'v');
Insert into SYSTEM.PROFIL (ID,NOM,PRENOM,DATEN,PHONE,MAILUP10,MAILPERSO,NATION,UNIV,PASS,AVATAR,DROIT) values ('pigeon2','r','R',to_date('11/05/16','DD/MM/RR'),'1234567890',null,'RED','fr','not','yolo',null,'v');
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("DROIT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("UNIV" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("NATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("MAILPERSO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("DATEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFIL" MODIFY ("ID" NOT NULL ENABLE);
