  CREATE TABLE "PROFIL"(
	"ID" VARCHAR(50) NOT NULL, 
	"NOM" VARCHAR(50)NOT NULL, 
	"PRENOM" VARCHAR(50)NOT NULL, 
	"DATEN" DATE NOT NULL, 
	"PHONE"  INTEGER NOT NULL, 
	"MAILUP10" VARCHAR(50), 
	"MAILPERSO" VARCHAR(50) NOT NULL, 
	"NATION" VARCHAR(50) NOT NULL, 
	"UNIV" VARCHAR(50) NOT NULL, 
	"PASS" VARCHAR(50) NOT NULL, 
	"AVATAR" DOUBLE, 
	"DROIT" VARCHAR(50) NOT NULL
   );